select PLAYER_GAME_ID,
       PLAYER_ID,
       GAME_ID,
       DATASET,
       DATE_OF_PLAY,
       OPP_TEAM,
       VENUE,
       MINS,
       FG,
       FGA,
       X3P,
       X3PA,
       FT,
       FTA,
       THE_OR,
       DR,
       TOT,
       A,
       PF,
       ST,
       THE_TO,
       BL,
       PTS
  from ATH_PLAYER_GAMES
 where player_id = :P120_PLAYER_ID